services:
  boks-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boks-api
    restart: always
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: boks-dev
      DB_PASSWORD: 123456
      DB_NAME: boks_db
      SECRET_TOKEN: boks-secret-jwt-key
    ports:
      - "8080:8080"
    networks:
      - boks-network
    depends_on:
      - postgres

  postgres:
    image: postgres:16
    container_name: boks-db
    restart: always
    environment:
      POSTGRES_USER: boks-dev
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: boks_db
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5432:5432"
    networks:
      - boks-network

volumes:
  pgdata:

networks:
  boks-network:
    driver: bridge
